"""
Visual Screenshot Verification Tool for UFO.
Scans task log directories in `logs/` (or a specified directory) and validates
all step PNG images (action_step*.png, desktop_step*.png, etc.).

Verification criteria per screenshot:
  a) Size > 1x1
  b) image.getbbox() is not None
  c) Pixel RGB stddev > 5.0 (using PIL.ImageStat)
  d) Non-empty image content (file size > 0 bytes and readable)
"""
import sys
import os
import argparse
from pathlib import Path
from typing import List, Tuple, Dict, Any
from PIL import Image, ImageStat

def is_diagnostic_warning_frame(img: Image.Image) -> bool:
    """
    Detect whether an image is a synthetic diagnostic warning banner frame
    generated by `_create_diagnostic_error_frame()` in ufo/automator/ui_control/screenshot.py.

    Synthetic error frames are dark canvases (RGB 30,30,35) with a 4-px red border
    (RGB 220,50,50) and warning text ("UFO SCREENSHOT CAPTURE WARNING").
    """
    if img is None:
        return False
    try:
        rgb_img = img.convert('RGB')
        w, h = rgb_img.size
        if w == 800 and h == 600:
            p_outer = rgb_img.getpixel((5, 5))
            p_border = rgb_img.getpixel((11, 11))
            p_inner = rgb_img.getpixel((20, 20))
            if p_outer == (30, 30, 35) and p_border == (220, 50, 50) and (p_inner == (30, 30, 35)):
                return True
        colors = rgb_img.getcolors(maxcolors=1000000)
        if colors:
            total_pixels = w * h
            bg_count = sum((cnt for cnt, col in colors if abs(col[0] - 30) <= 3 and abs(col[1] - 30) <= 3 and (abs(col[2] - 35) <= 3)))
            red_count = sum((cnt for cnt, col in colors if abs(col[0] - 220) <= 10 and abs(col[1] - 50) <= 10 and (abs(col[2] - 50) <= 10)))
            if bg_count / total_pixels > 0.75 and red_count / total_pixels > 0.005:
                return True
    except Exception:
        pass
    return False

def is_valid_step_image(image_path: str, min_stddev: float=5.0) -> Tuple[bool, str]:
    """
    Validate a single PNG screenshot image file.
    Returns (is_valid, status_message).
    """
    if not os.path.exists(image_path):
        return (False, 'File does not exist')
    file_size = os.path.getsize(image_path)
    if file_size == 0:
        return (False, 'File is empty (0 bytes)')
    try:
        with Image.open(image_path) as img:
            w, h = img.size
            if w <= 1 or h <= 1:
                return (False, f'Invalid dimensions ({w}x{h} <= 1x1)')
            bbox = img.getbbox()
            if bbox is None:
                return (False, 'Image is completely black/empty (getbbox() is None)')
            stat = ImageStat.Stat(img.convert('RGB'))
            max_stddev = max(stat.stddev) if stat.stddev else 0.0
            if max_stddev <= min_stddev:
                return (False, f'Low pixel stddev ({max_stddev:.2f} <= {min_stddev})')
            if is_diagnostic_warning_frame(img):
                return (False, 'Synthetic diagnostic warning card detected (no authentic UI capture)')
            return (True, f'Valid screenshot ({w}x{h}, size={file_size}B, stddev={max_stddev:.2f})')
    except Exception as e:
        return (False, f'Corrupted image or read failure: {e}')

def scan_and_verify_screenshots(target_dir: str, pattern: str='*.png', min_stddev: float=5.0) -> Dict[str, Any]:
    """
    Scan a directory (recursively) for PNG screenshots and verify each one.
    Returns a summary dict containing pass/fail metrics and details.
    """
    target_path = Path(target_dir).resolve()
    results: Dict[str, Any] = {'target_dir': str(target_path), 'total_scanned': 0, 'passed': 0, 'failed': 0, 'details': []}
    if not target_path.exists():
        print(f"Error: Target directory '{target_path}' does not exist.")
        return results
    png_files = sorted(list(target_path.glob(f'**/{pattern}')))
    results['total_scanned'] = len(png_files)
    for png_path in png_files:
        try:
            rel_path = str(png_path.relative_to(target_path))
        except ValueError:
            rel_path = str(png_path)
        valid, msg = is_valid_step_image(str(png_path), min_stddev=min_stddev)
        entry = {'path': str(png_path), 'relative_path': rel_path, 'valid': valid, 'message': msg}
        results['details'].append(entry)
        if valid:
            results['passed'] += 1
        else:
            results['failed'] += 1
    return results

def verify_task_screenshots(log_dir: str, min_stddev: float=5.0) -> bool:
    """
    Interface contract function as defined in PROJECT.md:
        pass
    verify_task_screenshots(log_dir) -> bool
    Returns True only if all step PNGs in log_dir contain valid, non-black UI screen renders.
    """
    results = scan_and_verify_screenshots(log_dir, pattern='*.png', min_stddev=min_stddev)
    if results['total_scanned'] == 0:
        print(f"[VERIFY] Warning: No PNG screenshots found in '{log_dir}'.")
        return False
    return results['failed'] == 0

def print_summary_report(results: Dict[str, Any]) -> None:
    """
    Print a structured, readable summary report of verification results.
    """
    print('=' * 80)
    print('              UFO VISUAL SCREENSHOT VERIFICATION REPORT             ')
    print('=' * 80)
    print(f"Target Directory: {results['target_dir']}")
    print(f"Total Screenshots Scanned: {results['total_scanned']}")
    print(f"Passed: {results['passed']}")
    print(f"Failed: {results['failed']}")
    print('-' * 80)
    if results['details']:
        print(f"{'Status':<8} | {'Relative Path':<48} | {'Details'}")
        print('-' * 80)
        for detail in results['details']:
            status_str = '[PASS]' if detail['valid'] else '[FAIL]'
            rel_p = detail['relative_path']
            if len(rel_p) > 48:
                rel_p = '...' + rel_p[-45:]
            print(f"{status_str:<8} | {rel_p:<48} | {detail['message']}")
        print('-' * 80)
    if results['total_scanned'] == 0:
        print('RESULT: WARNING — No screenshot files found in target directory.')
    elif results['failed'] == 0:
        print('RESULT: SUCCESS — All screenshots passed visual verification!')
    else:
        print(f"RESULT: FAILURE — {results['failed']} screenshot(s) failed visual verification.")
    print('=' * 80)

def main() -> None:
    parser = argparse.ArgumentParser(description='UFO Visual Screenshot Verification Tool')
    parser.add_argument('log_dir', nargs='?', default='logs', help='Path to logs directory or task directory to scan (default: logs)')
    parser.add_argument('--min-stddev', type=float, default=5.0, help='Minimum pixel RGB standard deviation threshold (default: 5.0)')
    parser.add_argument('--pattern', type=str, default='*.png', help='File glob pattern to match (default: *.png)')
    args = parser.parse_args()
    results = scan_and_verify_screenshots(target_dir=args.log_dir, pattern=args.pattern, min_stddev=args.min_stddev)
    print_summary_report(results)
    if results['total_scanned'] > 0 and results['failed'] == 0:
        sys.exit(0)
    else:
        sys.exit(1)
if __name__ == '__main__':
    main()